#!/bin/zsh
export BOOTSTRAP=${BOOTSTRAP:-$(dirname ${0})}
include_dir="$BOOTSTRAP/include"
includes=""
if [ -d $include_dir ]; then
  includes=`find -L $include_dir -maxdepth 1 -mindepth 1 -type d`
fi

export XDG_CONFIG_HOME=$BOOTSTRAP/.xdg/config
export XDG_DATA_HOME=$BOOTSTRAP/.xdg/data
export XDG_CACHE_HOME=$BOOTSTRAP/.xdg/cache
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/history"
mkdir -p $(dirname "$HISTFILE")

for include in ${=includes};
do
  dir_name=`basename "$include"`
  dir_name_upper=`echo $dir_name | tr '[a-z]' '[A-Z]'`
  eval export BOOTSTRAP_${dir_name_upper}="$include"
done
